rtux_Grub_Update_Config function was created. Grub install script was fixed.

diff --git a/update-grub/run b/update-grub/run
--- a/update-grub/run
+++ b/update-grub/run
@@ -6,91 +6,79 @@ source ${RESCATUX_LIB_FILE}
 set -x
 set -v
 
-$TARGET_PARTITIONS=$(rtux_Choose_HardDisk_Renaming)
 
-# TODO: Program check runtime (Maybe to be stolen from bootinfoscript)
+# Update Grub configuration file from the choosen Linux partition
+# 1 parametre = Selected partition
+# While it is being run user is shown the hard disks
+# and it is asked to order them
+function rtux_Grub_Update_Config () {
+# TODO: Extract last user interaction (Success/Failure)
+# So that this function returns being successful or not
 
-SBIN_GRUB_PARTITIONS="$(rtux_Get_Linux_Os_Partitions)"
+  local DETECTED_HARD_DISKS=$(rtux_Get_System_HardDisks);
+  local SELECTED_PARTITION=$1;
+  local n_partition=${SELECTED_PARTITION}
 
-UPDATE_GRUB_BINARY=update-grub
+  local TMP_MNT_PARTITION=${RESCATUX_ROOT_MNT}/${n_partition}
+  local TMP_DEV_PARTITION=/dev/${n_partition}
+  mkdir --parents ${TMP_MNT_PARTITION}
 
-# MAIN PROGRAM
+  if $(mount -t auto ${TMP_DEV_PARTITION} ${TMP_MNT_PARTITION} 2> /dev/null)
+    then
+    mount -o bind /dev ${TMP_MNT_PARTITION}/dev
+    mount -o bind /proc ${TMP_MNT_PARTITION}/proc
+    mount -o bind /sys ${TMP_MNT_PARTITION}/sys
 
-DEVICE_MAP_NUMBERED_FILE="${TMP_FOLDER}/device.map.numbered"
-DEVICE_MAP_RESCATUX_STR="device.map.rescatux"
-DEVICE_MAP_BACKUP_STR="device.map.rescatux.backup"
+    if [[ -e ${TMP_MNT_PARTITION}${LINUX_OS_DETECTOR} ]] ; then
+      # Generate temporal device.map file in / (Chroot's root but outside chroot) - TODO - BEGIN
+      # (Fetch hard disks detected and show to the user. - TODO - BEGIN
+      # Tell them that they are going to be asked to choose which it is #1, #2,...)
+      $(rtux_Choose_Hard_Disk ${PREPARE_ORDER_HDS_STR});
+   
+      # (Fetch hard disks detected and show to the user. - TODO - END
+      # Tell them that they are going to be asked to choose which it is #1, #2,...)
+      # LOOP - Show hard disk and ask position - TODO - BEGIN
+      echo "" > ${DEVICE_MAP_NUMBERED_FILE}
+      local n=1
+      local HD_LIST_VALUES=""
+      for n_hard_disk in ${DETECTED_HARD_DISKS}; do
+	m=1
+	for m_hard_disk in ${DETECTED_HARD_DISKS}; do			      
+	  if [[ m -eq 1 ]] ; then
+	    HD_LIST_VALUES="TRUE ${m} ${n_hard_disk} \
+	      `/sbin/fdisk -l /dev/${n_hard_disk} \
+		      | egrep 'Disk.*bytes' \
+		      | awk '{ sub(/,/,"");  print $3 "-" $4 }'`"
+	  else
+	    HD_LIST_VALUES="${HD_LIST_VALUES} FALSE ${m} ${n_hard_disk} \
+	    `/sbin/fdisk -l /dev/${n_hard_disk} \
+		      | egrep 'Disk.*bytes' \
+		      | awk '{ sub(/,/,"");  print $3 "-" $4 }'`"
+	  fi
+	  let m=m+1
+	done
 
-UPDATE_GRUB_OK_STR="Grub configuration was updated OK! :)"
-UPDATE_GRUB_KO_STR="Grub configuration update went wrong! :("
+	# Ask position - BEGIN
+	local SELECTED_POSITION=$(zenity ${ZENITY_COMMON_OPTIONS} \
+	      --list  \
+	      --text "${RIGHT_HD_POSITION_STR}" \
+	      --radiolist  \
+	      --column "${SELECT_STR}" \
+	      --column "${POSITION_STR}" \
+	      --column "${HARDDISK_STR}" \
+	      ${HD_LIST_VALUES}); 
 
-SELECTED_PARTITION=$(rtux_Choose_Linux_partition);
-
-DETECTED_HARD_DISKS=$(rtux_Get_System_HardDisks);
-
-n_partition=${SELECTED_PARTITION}
-
-TMP_MNT_PARTITION=${RESCATUX_ROOT_MNT}/${n_partition}
-TMP_DEV_PARTITION=/dev/${n_partition}
-mkdir --parents ${TMP_MNT_PARTITION}
-if $(mount -t auto ${TMP_DEV_PARTITION} ${TMP_MNT_PARTITION} 2> /dev/null) ; then
-	mount -o bind /dev ${TMP_MNT_PARTITION}/dev
-	mount -o bind /proc ${TMP_MNT_PARTITION}/proc
-	mount -o bind /sys ${TMP_MNT_PARTITION}/sys
-
-
-	#echo -e -n "Detected partition is: ${n_partition}\n";
-	if [[ -e ${TMP_MNT_PARTITION}${LINUX_OS_DETECTOR} ]] ; then
-
-
-
-		# Generate temporal device.map file in / (Chroot's root but outside chroot) - TODO - BEGIN
-		    # (Fetch hard disks detected and show to the user. - TODO - BEGIN
-		    # Tell them that they are going to be asked to choose which it is #1, #2,...)
-		    $(rtux_Choose_Hard_Disk ${PREPARE_ORDER_HDS_STR});      
-		    # (Fetch hard disks detected and show to the user. - TODO - END
-		    # Tell them that they are going to be asked to choose which it is #1, #2,...)
-		    # LOOP - Show hard disk and ask position - TODO - BEGIN
-		    echo "" > ${DEVICE_MAP_NUMBERED_FILE}
-		    n=1
-		    local HD_LIST_VALUES=""
-		    for n_hard_disk in ${DETECTED_HARD_DISKS}; do
-		      m=1
-		      for m_hard_disk in ${DETECTED_HARD_DISKS}; do			      
-			if [[ m -eq 1 ]] ; then
-			  HD_LIST_VALUES="TRUE ${m} ${n_hard_disk} \
-			  `/sbin/fdisk -l /dev/${n_hard_disk} \
-				    | egrep 'Disk.*bytes' \
-				    | awk '{ sub(/,/,"");  print $3 "-" $4 }'`"
-			else
-			  HD_LIST_VALUES="${HD_LIST_VALUES} FALSE ${m} ${n_hard_disk} \
-			  `/sbin/fdisk -l /dev/${n_hard_disk} \
-				    | egrep 'Disk.*bytes' \
-				    | awk '{ sub(/,/,"");  print $3 "-" $4 }'`"
-			fi
-			let m=m+1
-		      done
-
-		      # Ask position - BEGIN
-		      local SELECTED_POSITION=$(zenity ${ZENITY_COMMON_OPTIONS} \
-			    --list  \
-			    --text "${RIGHT_HD_POSITION_STR}" \
-			    --radiolist  \
-			    --column "${SELECT_STR}" \
-			    --column "${POSITION_STR}" \
-			    --column "${HARDDISK_STR}" \
-			    ${HD_LIST_VALUES}); 
-
-		      # Ask position - END
-		      # Generate temporal file with order - TODO - BEGIN
-		      echo -e -n "${SELECTED_POSITION} (hd$(( ${SELECTED_POSITION} - 1 ))) /dev/${n_hard_disk}\n" >> ${DEVICE_MAP_NUMBERED_FILE}
-		      # Generate temporal file with order - TODO - END
-		      let n=n+1
-		    done
-		      # Generate a temporal txt file that begins with a number in first column
-		    # LOOP - Show hard disk and ask position - TODO - END
-		    # Read the temporal txt file, sort by first column and generate device.map file
-		    cat ${DEVICE_MAP_NUMBERED_FILE} | sort | awk '{printf("%s\t%s\n",$2,$3);}' > ${TMP_MNT_PARTITION}/${DEVICE_MAP_RESCATUX_STR}
-		# Generate temporal device.map file in / (Chroot's root but outside chroot) - TODO - END
+	# Ask position - END
+	# Generate temporal file with order - TODO - BEGIN
+	echo -e -n "${SELECTED_POSITION} (hd$(( ${SELECTED_POSITION} - 1 ))) /dev/${n_hard_disk}\n" >> ${DEVICE_MAP_NUMBERED_FILE}
+	# Generate temporal file with order - TODO - END
+	let n=n+1
+      done
+	# Generate a temporal txt file that begins with a number in first column
+      # LOOP - Show hard disk and ask position - TODO - END
+      # Read the temporal txt file, sort by first column and generate device.map file
+      cat ${DEVICE_MAP_NUMBERED_FILE} | sort | awk '{printf("%s\t%s\n",$2,$3);}' > ${TMP_MNT_PARTITION}/${DEVICE_MAP_RESCATUX_STR}
+      # Generate temporal device.map file in / (Chroot's root but outside chroot) - TODO - END
 
 
       # TODO: Improve with a cat command ended with a EOF mark
@@ -109,8 +97,7 @@ if $(mount -t auto ${TMP_DEV_PARTITION} ${TMP_MNT_PARTITION} 2> /dev/null) ; the
 	# Overwrite current device.map file with temporal device.map (inside chroot) - TODO - END
 
 	${UPDATE_GRUB_BINARY}
-
-UPDATE_GRUB_OUTPUT=\$?
+	UPDATE_GRUB_OUTPUT=\$?
 
 	# Restore current device.map file - BEGIN
 	cp /boot/grub/${DEVICE_MAP_BACKUP_STR} /boot/grub/device.map
@@ -120,7 +107,7 @@ UPDATE_GRUB_OUTPUT=\$?
 	rm /${DEVICE_MAP_RESCATUX_STR}
 	# Delete temporal and backup device.map files- TODO - END
 	umount -a
-		exit \${UPDATE_GRUB_OUTPUT}"
+	exit \${UPDATE_GRUB_OUTPUT}"
 EOF
 
       chmod +x ${TMP_MNT_PARTITION_SCRIPT}
@@ -137,13 +124,32 @@ EOF
       rm ${TMP_MNT_PARTITION_SCRIPT}
 		
 
-	fi
-	umount ${TMP_MNT_PARTITION}/sys
-	umount ${TMP_MNT_PARTITION}/proc
-	umount ${TMP_MNT_PARTITION}/dev
-	umount ${TMP_MNT_PARTITION};
-fi
+    fi # Linux detector was found
+    umount ${TMP_MNT_PARTITION}/sys
+    umount ${TMP_MNT_PARTITION}/proc
+    umount ${TMP_MNT_PARTITION}/dev
+    umount ${TMP_MNT_PARTITION};
+  fi # Partition was mounted ok
+
+} # function rtux_Grub_Update_Config ()
 
 
+# TODO: Program check runtime (Maybe to be stolen from bootinfoscript)
+
+
+
+UPDATE_GRUB_BINARY=update-grub
+
+# MAIN PROGRAM
+
+DEVICE_MAP_NUMBERED_FILE="${TMP_FOLDER}/device.map.numbered"
+DEVICE_MAP_RESCATUX_STR="device.map.rescatux"
+DEVICE_MAP_BACKUP_STR="device.map.rescatux.backup"
+
+UPDATE_GRUB_OK_STR="Grub configuration was updated OK! :)"
+UPDATE_GRUB_KO_STR="Grub configuration update went wrong! :("
+
+
+rtux_Grub_Update_Config $(rtux_Choose_Linux_partition)
 
 #
